name: mobileapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  url_launcher: ^6.0.20
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/nps.jpg 
    - assets/icons/facebook.png
    - assets/icons/github.png
    - assets/icons/twitterrr.png
    - assets/picture/nsc.jpg
    - assets/cipher/Vigenere.jpg
    - assets/cipher/Atbash.jpg
    - assets/cipher/Caesar.jpg